version: '3.8'

services:
  atrpg:
    image: atrpg:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./src/connexion_example.php:/var/www/html/connexion.php
    ports:
      - "80:80"

  serveur-mysql:
    image: mysql:5.7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password-to-change
      MYSQL_DATABASE: nombase
      MYSQL_USER: login
      MYSQL_PASSWORD: mdp

